---
swagger: "2.0"
info:
  description: "This is a sample Petstore server.  You can find \nout more about Swagger\
    \ at \n[http://swagger.io](http://swagger.io) or on \n[irc.freenode.net, #swagger](http://swagger.io/irc/).\n"
  version: "1.0.0"
  title: "Swagger Petstore"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "apiteam@swagger.io"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "localhost:8080"
basePath: "/cs-739/DiskFailurePrediction/1.0.0"
schemes:
- "https"
- "http"
security:
- api_key: []
paths:
  /smart-ssd:
    get:
      tags:
      - "smart data"
      summary: "Get all ssd disk data"
      operationId: "get_smart_ssd"
      parameters: []
      responses:
        405:
          description: "Invalid input"
      x-swagger-router-controller: "swagger_server.controllers.smart_data_controller"
    post:
      tags:
      - "smart data"
      summary: "Upload ssd disk data"
      operationId: "add_smart_ssd"
      consumes:
      - "application/json"
      parameters:
      - name: "UUID"
        in: "query"
        description: "Unique User ID"
        required: false
        type: "string"
      - in: "body"
        name: "smartSsd"
        description: "Smartctl --json -x output to be added to dataset"
        required: true
        schema:
          $ref: "#/definitions/SmartSsd"
      responses:
        405:
          description: "Invalid input"
      x-swagger-router-controller: "swagger_server.controllers.smart_data_controller"
  /smart-nvme:
    get:
      tags:
      - "smart data"
      summary: "Get all NVME disk data"
      operationId: "get_smart_nvme"
      parameters: []
      responses:
        405:
          description: "Invalid input"
      x-swagger-router-controller: "swagger_server.controllers.smart_data_controller"
    post:
      tags:
      - "smart data"
      summary: "Upload NVME disk data"
      operationId: "add_smart_nvme"
      consumes:
      - "application/json"
      parameters:
      - name: "UUID"
        in: "query"
        description: "Unique User ID"
        required: false
        type: "string"
      - in: "body"
        name: "smartNvme"
        description: "Smartctl --json -x output to be added to dataset"
        required: true
        schema:
          $ref: "#/definitions/SmartNvme"
      responses:
        405:
          description: "Invalid input"
      x-swagger-router-controller: "swagger_server.controllers.smart_data_controller"
  /auth:
    post:
      tags:
      - "Auth"
      summary: "Generate new UUID and API Key"
      operationId: "get_auth"
      parameters:
      - name: "UUID"
        in: "query"
        description: "Unique User ID"
        required: false
        type: "string"
      responses:
        200:
          description: "Success"
          schema:
            $ref: "#/definitions/inline_response_200"
        405:
          description: "Invalid input"
      x-swagger-router-controller: "swagger_server.controllers.auth_controller"
securityDefinitions:
  api_key:
    type: "apiKey"
    name: "Authorization"
    in: "header"
definitions:
  SmartNvme:
    type: "object"
    properties:
      json_format_version:
        type: "array"
        items:
          type: "integer"
          format: "int32"
      smartctl:
        $ref: "#/definitions/SmartNvme_smartctl"
      device:
        $ref: "#/definitions/SmartNvme_device"
      model_name:
        type: "string"
      serial_number:
        type: "string"
      firmware_version:
        type: "string"
      nvme_pci_vendor:
        $ref: "#/definitions/SmartNvme_nvme_pci_vendor"
      nvme_ieee_oui_identifier:
        type: "integer"
        format: "int32"
      nvme_controller_id:
        type: "integer"
        format: "int32"
      nvme_number_of_namespaces:
        type: "integer"
        format: "int32"
      nvme_namespaces:
        type: "array"
        items:
          $ref: "#/definitions/SmartNvme_nvme_namespaces"
      user_capacity:
        $ref: "#/definitions/SmartNvme_size"
      logical_block_size:
        type: "integer"
        format: "int32"
      local_time:
        $ref: "#/definitions/SmartNvme_local_time"
      smart_status:
        $ref: "#/definitions/SmartNvme_smart_status"
      nvme_smart_health_information_log:
        $ref: "#/definitions/SmartNvme_nvme_smart_health_information_log"
      temperature:
        $ref: "#/definitions/SmartNvme_temperature"
      power_cycle_count:
        type: "integer"
        format: "int32"
      power_on_time:
        $ref: "#/definitions/SmartNvme_power_on_time"
    example:
      smartctl:
        platform_info: "platform_info"
        exit_status: 1
        version:
        - 6
        - 6
        argv:
        - "argv"
        - "argv"
        build_info: "build_info"
        svn_revision: "svn_revision"
      logical_block_size: 1
      smart_status:
        nvme:
          value: 1
        passed: true
      serial_number: "serial_number"
      firmware_version: "firmware_version"
      nvme_pci_vendor:
        subsystem_id: 1
        id: 6
      model_name: "model_name"
      nvme_ieee_oui_identifier: 5
      local_time:
        asctime: "asctime"
        time_t: 6
      user_capacity:
        blocks: 9
        bytes: 3
      power_on_time:
        hours: 6
      power_cycle_count: 5
      temperature:
        current: 6
      nvme_smart_health_information_log:
        controller_busy_time: 8
        data_units_read: 5
        power_cycles: 9
        available_spare_threshold: 1
        host_reads: 9
        unsafe_shutdowns: 3
        media_errors: 6
        warning_temp_time: 2
        critical_comp_time: 6
        power_on_hours: 6
        host_writes: 6
        critical_warning: 1
        percentage_used: 4
        temperature: 6
        available_spare: 7
        data_units_written: 9
        num_err_log_entries: 1
      json_format_version:
      - 0
      - 0
      device:
        protocol: "protocol"
        name: "name"
        info_name: "info_name"
        type: "type"
      nvme_number_of_namespaces: 2
      nvme_controller_id: 5
      nvme_namespaces:
      - eui64:
          oui: 4
          ext_id: 7
        size:
          blocks: 9
          bytes: 3
        utilization:
          blocks: 9
          bytes: 3
        id: 7
        capacity:
          blocks: 9
          bytes: 3
        formatted_lba_size: 2
      - eui64:
          oui: 4
          ext_id: 7
        size:
          blocks: 9
          bytes: 3
        utilization:
          blocks: 9
          bytes: 3
        id: 7
        capacity:
          blocks: 9
          bytes: 3
        formatted_lba_size: 2
  SmartSsd:
    type: "object"
    properties:
      json_format_version:
        type: "array"
        items:
          type: "integer"
          format: "int32"
      smartctl:
        $ref: "#/definitions/SmartNvme_smartctl"
      device:
        $ref: "#/definitions/SmartNvme_device"
      model_family:
        type: "string"
      model_name:
        type: "string"
      serial_number:
        type: "string"
      wwn:
        $ref: "#/definitions/SmartSsd_wwn"
      firmware_version:
        type: "string"
      user_capacity:
        $ref: "#/definitions/SmartSsd_user_capacity"
      logical_block_size:
        type: "integer"
        format: "int32"
      physical_block_size:
        type: "integer"
        format: "int32"
      rotation_rate:
        type: "integer"
        format: "int32"
      form_factor:
        $ref: "#/definitions/SmartSsd_form_factor"
      in_smartctl_database:
        type: "boolean"
      ata_version:
        $ref: "#/definitions/SmartSsd_ata_version"
      sata_version:
        $ref: "#/definitions/SmartSsd_sata_version"
      interface_speed:
        $ref: "#/definitions/SmartSsd_interface_speed"
      local_time:
        $ref: "#/definitions/SmartNvme_local_time"
      read_lookahead:
        $ref: "#/definitions/SmartSsd_read_lookahead"
      write_cache:
        $ref: "#/definitions/SmartSsd_read_lookahead"
      ata_security:
        $ref: "#/definitions/SmartSsd_ata_security"
      smart_status:
        $ref: "#/definitions/SmartSsd_smart_status"
      ata_smart_data:
        $ref: "#/definitions/SmartSsd_ata_smart_data"
      ata_sct_capabilities:
        $ref: "#/definitions/SmartSsd_ata_sct_capabilities"
      ata_smart_attributes:
        $ref: "#/definitions/SmartSsd_ata_smart_attributes"
      temperature:
        $ref: "#/definitions/SmartSsd_temperature"
      ata_log_directory:
        $ref: "#/definitions/SmartSsd_ata_log_directory"
      ata_smart_error_log:
        $ref: "#/definitions/SmartSsd_ata_smart_error_log"
      ata_smart_self_test_log:
        $ref: "#/definitions/SmartSsd_ata_smart_error_log"
      ata_sct_status:
        $ref: "#/definitions/SmartSsd_ata_sct_status"
      ata_sct_temperature_history:
        $ref: "#/definitions/SmartSsd_ata_sct_temperature_history"
      ata_sct_erc:
        $ref: "#/definitions/SmartSsd_ata_sct_erc"
      sata_phy_event_counters:
        $ref: "#/definitions/SmartSsd_sata_phy_event_counters"
    example:
      smartctl:
        platform_info: "platform_info"
        exit_status: 1
        version:
        - 6
        - 6
        argv:
        - "argv"
        - "argv"
        build_info: "build_info"
        svn_revision: "svn_revision"
      ata_version:
        major_value: 1
        string: "string"
        minor_value: 1
      in_smartctl_database: true
      firmware_version: "firmware_version"
      write_cache:
        enabled: true
      wwn:
        oui: 5
        id: 2
        naa: 5
      ata_sct_erc:
        read:
          enabled: true
        write:
          enabled: true
      model_name: "model_name"
      local_time:
        asctime: "asctime"
        time_t: 6
      ata_smart_error_log:
        extended:
          sectors: 7
          count: 5
          revision: 3
      user_capacity:
        blocks:
          s: "s"
          n: 7
        bytes:
          s: "s"
          n: 9
      read_lookahead:
        enabled: true
      temperature:
        op_limit_max: 0
        current: 6
        op_limit_min: 7
        limit_min: 7
        power_cycle_max: 6
        lifetime_min: 3
        power_cycle_min: 5
        lifetime_max: 3
        limit_max: 6
      ata_log_directory:
        smart_dir_multi_sector: true
        gp_dir_version: 0
        table:
        - address: 8
          read: true
          name: "name"
          gp_sectors: 7
          smart_sectors: 3
          write: true
        - address: 8
          read: true
          name: "name"
          gp_sectors: 7
          smart_sectors: 3
          write: true
        smart_dir_version: 4
      interface_speed:
        current:
          string: "string"
        max:
          string: "string"
      ata_smart_self_test_log:
        extended:
          sectors: 7
          count: 5
          revision: 3
      ata_smart_data:
        self_test:
          polling_minutes:
            conveyance: 6
            short: 9
            extended: 9
          status:
            string: "string"
            passed: true
            value: 5
        capabilities:
          exec_offline_immediate_supported: true
          self_tests_supported: true
          selective_self_test_supported: true
          offline_is_aborted_upon_new_cmd: true
          conveyance_self_test_supported: true
          values:
          - 8
          - 8
          offline_surface_scan_supported: true
          error_logging_supported: true
          gp_logging_supported: true
          attribute_autosave_enabled: true
        offline_data_collection:
          completion_seconds: 4
          status:
            string: "string"
            value: 1
      json_format_version:
      - 0
      - 0
      physical_block_size: 2
      logical_block_size: 3
      ata_sct_temperature_history:
        size: 4
        logging_interval_minutes: 7
        sampling_period_minutes: 0
        temperature:
          op_limit_max: 4
          op_limit_min: 5
          limit_min: 6
          limit_max: 8
        index: 3
        version: 9
        table:
        - 0
        - 0
      smart_status:
        passed: true
      ata_smart_attributes:
        table:
        - name: "name"
          flags:
            error_rate: true
            performance: true
            string: "string"
            updated_online: true
            auto_keep: true
            event_count: true
            prefailure: true
            value: 6
          raw:
            string: "string"
            value: 1
          worst: 1
          id: 3
          value: 6
          thresh: 2
          when_failed: "when_failed"
        - name: "name"
          flags:
            error_rate: true
            performance: true
            string: "string"
            updated_online: true
            auto_keep: true
            event_count: true
            prefailure: true
            value: 6
          raw:
            string: "string"
            value: 1
          worst: 1
          id: 3
          value: 6
          thresh: 2
          when_failed: "when_failed"
        revision: 6
      ata_sct_capabilities:
        data_table_supported: true
        feature_control_supported: true
        value: 9
        error_recovery_control_supported: true
      serial_number: "serial_number"
      rotation_rate: 4
      ata_security:
        string: "string"
        frozen: true
        state: 7
        enabled: true
      ata_sct_status:
        device_state:
          string: "string"
          value: 1
        format_version: 3
        sct_version: 4
        temperature:
          current: 0
          power_cycle_max: 4
          lifetime_min: 1
          over_limit_count: 9
          power_cycle_min: 6
          lifetime_max: 4
          under_limit_count: 7
        vendor_specific:
        - 0
        - 0
      sata_version:
        string: "string"
        value: 1
      device:
        protocol: "protocol"
        name: "name"
        info_name: "info_name"
        type: "type"
      sata_phy_event_counters:
        reset: true
        table:
        - overflow: true
          size: 1
          name: "name"
          id: 2
          value: 8
        - overflow: true
          size: 1
          name: "name"
          id: 2
          value: 8
      model_family: "model_family"
      form_factor:
        name: "name"
        ata_value: 7
  SmartNvme_smartctl:
    properties:
      version:
        type: "array"
        items:
          type: "integer"
          format: "int32"
      svn_revision:
        type: "string"
      platform_info:
        type: "string"
      build_info:
        type: "string"
      argv:
        type: "array"
        items:
          type: "string"
      exit_status:
        type: "integer"
        format: "int32"
    example:
      platform_info: "platform_info"
      exit_status: 1
      version:
      - 6
      - 6
      argv:
      - "argv"
      - "argv"
      build_info: "build_info"
      svn_revision: "svn_revision"
  SmartNvme_device:
    properties:
      name:
        type: "string"
      info_name:
        type: "string"
      type:
        type: "string"
      protocol:
        type: "string"
    example:
      protocol: "protocol"
      name: "name"
      info_name: "info_name"
      type: "type"
  SmartNvme_nvme_pci_vendor:
    properties:
      id:
        type: "integer"
        format: "int32"
      subsystem_id:
        type: "integer"
        format: "int32"
    example:
      subsystem_id: 1
      id: 6
  SmartNvme_size:
    properties:
      blocks:
        type: "integer"
        format: "int32"
      bytes:
        type: "integer"
        format: "int64"
    example:
      blocks: 9
      bytes: 3
  SmartNvme_eui64:
    properties:
      oui:
        type: "integer"
        format: "int32"
      ext_id:
        type: "integer"
        format: "int64"
    example:
      oui: 4
      ext_id: 7
  SmartNvme_nvme_namespaces:
    properties:
      id:
        type: "integer"
        format: "int32"
      size:
        $ref: "#/definitions/SmartNvme_size"
      capacity:
        $ref: "#/definitions/SmartNvme_size"
      utilization:
        $ref: "#/definitions/SmartNvme_size"
      formatted_lba_size:
        type: "integer"
        format: "int32"
      eui64:
        $ref: "#/definitions/SmartNvme_eui64"
    example:
      eui64:
        oui: 4
        ext_id: 7
      size:
        blocks: 9
        bytes: 3
      utilization:
        blocks: 9
        bytes: 3
      id: 7
      capacity:
        blocks: 9
        bytes: 3
      formatted_lba_size: 2
  SmartNvme_local_time:
    properties:
      time_t:
        type: "integer"
        format: "int32"
      asctime:
        type: "string"
    example:
      asctime: "asctime"
      time_t: 6
  SmartNvme_smart_status_nvme:
    properties:
      value:
        type: "integer"
        format: "int32"
    example:
      value: 1
  SmartNvme_smart_status:
    properties:
      passed:
        type: "boolean"
      nvme:
        $ref: "#/definitions/SmartNvme_smart_status_nvme"
    example:
      nvme:
        value: 1
      passed: true
  SmartNvme_nvme_smart_health_information_log:
    properties:
      critical_warning:
        type: "integer"
        format: "int32"
      temperature:
        type: "integer"
        format: "int32"
      available_spare:
        type: "integer"
        format: "int32"
      available_spare_threshold:
        type: "integer"
        format: "int32"
      percentage_used:
        type: "integer"
        format: "int32"
      data_units_read:
        type: "integer"
        format: "int32"
      data_units_written:
        type: "integer"
        format: "int32"
      host_reads:
        type: "integer"
        format: "int64"
      host_writes:
        type: "integer"
        format: "int64"
      controller_busy_time:
        type: "integer"
        format: "int32"
      power_cycles:
        type: "integer"
        format: "int32"
      power_on_hours:
        type: "integer"
        format: "int32"
      unsafe_shutdowns:
        type: "integer"
        format: "int32"
      media_errors:
        type: "integer"
        format: "int32"
      num_err_log_entries:
        type: "integer"
        format: "int32"
      warning_temp_time:
        type: "integer"
        format: "int32"
      critical_comp_time:
        type: "integer"
        format: "int32"
    example:
      controller_busy_time: 8
      data_units_read: 5
      power_cycles: 9
      available_spare_threshold: 1
      host_reads: 9
      unsafe_shutdowns: 3
      media_errors: 6
      warning_temp_time: 2
      critical_comp_time: 6
      power_on_hours: 6
      host_writes: 6
      critical_warning: 1
      percentage_used: 4
      temperature: 6
      available_spare: 7
      data_units_written: 9
      num_err_log_entries: 1
  SmartNvme_temperature:
    properties:
      current:
        type: "integer"
        format: "int32"
    example:
      current: 6
  SmartNvme_power_on_time:
    properties:
      hours:
        type: "integer"
        format: "int32"
    example:
      hours: 6
  SmartSsd_wwn:
    properties:
      naa:
        type: "integer"
        format: "int32"
      oui:
        type: "integer"
        format: "int32"
      id:
        type: "integer"
        format: "int32"
    example:
      oui: 5
      id: 2
      naa: 5
  SmartSsd_user_capacity_blocks:
    properties:
      n:
        type: "integer"
        format: "int32"
      s:
        type: "string"
    example:
      s: "s"
      n: 7
  SmartSsd_user_capacity_bytes:
    properties:
      n:
        type: "integer"
        format: "int64"
      s:
        type: "string"
    example:
      s: "s"
      n: 9
  SmartSsd_user_capacity:
    properties:
      blocks:
        $ref: "#/definitions/SmartSsd_user_capacity_blocks"
      bytes:
        $ref: "#/definitions/SmartSsd_user_capacity_bytes"
    example:
      blocks:
        s: "s"
        n: 7
      bytes:
        s: "s"
        n: 9
  SmartSsd_form_factor:
    properties:
      ata_value:
        type: "integer"
        format: "int32"
      name:
        type: "string"
    example:
      name: "name"
      ata_value: 7
  SmartSsd_ata_version:
    properties:
      string:
        type: "string"
      major_value:
        type: "integer"
        format: "int32"
      minor_value:
        type: "integer"
        format: "int32"
    example:
      major_value: 1
      string: "string"
      minor_value: 1
  SmartSsd_sata_version:
    properties:
      string:
        type: "string"
      value:
        type: "integer"
        format: "int32"
    example:
      string: "string"
      value: 1
  SmartSsd_interface_speed_max:
    properties:
      string:
        type: "string"
    example:
      string: "string"
  SmartSsd_interface_speed:
    properties:
      max:
        $ref: "#/definitions/SmartSsd_interface_speed_max"
      current:
        $ref: "#/definitions/SmartSsd_interface_speed_max"
    example:
      current:
        string: "string"
      max:
        string: "string"
  SmartSsd_read_lookahead:
    properties:
      enabled:
        type: "boolean"
    example:
      enabled: true
  SmartSsd_ata_security:
    properties:
      state:
        type: "integer"
        format: "int32"
      string:
        type: "string"
      enabled:
        type: "boolean"
      frozen:
        type: "boolean"
    example:
      string: "string"
      frozen: true
      state: 7
      enabled: true
  SmartSsd_smart_status:
    properties:
      passed:
        type: "boolean"
    example:
      passed: true
  SmartSsd_ata_smart_data_offline_data_collection_status:
    properties:
      value:
        type: "integer"
        format: "int32"
      string:
        type: "string"
    example:
      string: "string"
      value: 1
  SmartSsd_ata_smart_data_offline_data_collection:
    properties:
      status:
        $ref: "#/definitions/SmartSsd_ata_smart_data_offline_data_collection_status"
      completion_seconds:
        type: "integer"
        format: "int32"
    example:
      completion_seconds: 4
      status:
        string: "string"
        value: 1
  SmartSsd_ata_smart_data_self_test_status:
    properties:
      value:
        type: "integer"
        format: "int32"
      string:
        type: "string"
      passed:
        type: "boolean"
    example:
      string: "string"
      passed: true
      value: 5
  SmartSsd_ata_smart_data_self_test_polling_minutes:
    properties:
      short:
        type: "integer"
        format: "int32"
      extended:
        type: "integer"
        format: "int32"
      conveyance:
        type: "integer"
        format: "int32"
    example:
      conveyance: 6
      short: 9
      extended: 9
  SmartSsd_ata_smart_data_self_test:
    properties:
      status:
        $ref: "#/definitions/SmartSsd_ata_smart_data_self_test_status"
      polling_minutes:
        $ref: "#/definitions/SmartSsd_ata_smart_data_self_test_polling_minutes"
    example:
      polling_minutes:
        conveyance: 6
        short: 9
        extended: 9
      status:
        string: "string"
        passed: true
        value: 5
  SmartSsd_ata_smart_data_capabilities:
    properties:
      values:
        type: "array"
        items:
          type: "integer"
          format: "int32"
      exec_offline_immediate_supported:
        type: "boolean"
      offline_is_aborted_upon_new_cmd:
        type: "boolean"
      offline_surface_scan_supported:
        type: "boolean"
      self_tests_supported:
        type: "boolean"
      conveyance_self_test_supported:
        type: "boolean"
      selective_self_test_supported:
        type: "boolean"
      attribute_autosave_enabled:
        type: "boolean"
      error_logging_supported:
        type: "boolean"
      gp_logging_supported:
        type: "boolean"
    example:
      exec_offline_immediate_supported: true
      self_tests_supported: true
      selective_self_test_supported: true
      offline_is_aborted_upon_new_cmd: true
      conveyance_self_test_supported: true
      values:
      - 8
      - 8
      offline_surface_scan_supported: true
      error_logging_supported: true
      gp_logging_supported: true
      attribute_autosave_enabled: true
  SmartSsd_ata_smart_data:
    properties:
      offline_data_collection:
        $ref: "#/definitions/SmartSsd_ata_smart_data_offline_data_collection"
      self_test:
        $ref: "#/definitions/SmartSsd_ata_smart_data_self_test"
      capabilities:
        $ref: "#/definitions/SmartSsd_ata_smart_data_capabilities"
    example:
      self_test:
        polling_minutes:
          conveyance: 6
          short: 9
          extended: 9
        status:
          string: "string"
          passed: true
          value: 5
      capabilities:
        exec_offline_immediate_supported: true
        self_tests_supported: true
        selective_self_test_supported: true
        offline_is_aborted_upon_new_cmd: true
        conveyance_self_test_supported: true
        values:
        - 8
        - 8
        offline_surface_scan_supported: true
        error_logging_supported: true
        gp_logging_supported: true
        attribute_autosave_enabled: true
      offline_data_collection:
        completion_seconds: 4
        status:
          string: "string"
          value: 1
  SmartSsd_ata_sct_capabilities:
    properties:
      value:
        type: "integer"
        format: "int32"
      error_recovery_control_supported:
        type: "boolean"
      feature_control_supported:
        type: "boolean"
      data_table_supported:
        type: "boolean"
    example:
      data_table_supported: true
      feature_control_supported: true
      value: 9
      error_recovery_control_supported: true
  SmartSsd_ata_smart_attributes_flags:
    properties:
      value:
        type: "integer"
        format: "int32"
      string:
        type: "string"
      prefailure:
        type: "boolean"
      updated_online:
        type: "boolean"
      performance:
        type: "boolean"
      error_rate:
        type: "boolean"
      event_count:
        type: "boolean"
      auto_keep:
        type: "boolean"
    example:
      error_rate: true
      performance: true
      string: "string"
      updated_online: true
      auto_keep: true
      event_count: true
      prefailure: true
      value: 6
  SmartSsd_ata_smart_attributes_table:
    properties:
      id:
        type: "integer"
        format: "int32"
      name:
        type: "string"
      value:
        type: "integer"
        format: "int32"
      worst:
        type: "integer"
        format: "int32"
      thresh:
        type: "integer"
        format: "int32"
      when_failed:
        type: "string"
      flags:
        $ref: "#/definitions/SmartSsd_ata_smart_attributes_flags"
      raw:
        $ref: "#/definitions/SmartSsd_ata_smart_data_offline_data_collection_status"
    example:
      name: "name"
      flags:
        error_rate: true
        performance: true
        string: "string"
        updated_online: true
        auto_keep: true
        event_count: true
        prefailure: true
        value: 6
      raw:
        string: "string"
        value: 1
      worst: 1
      id: 3
      value: 6
      thresh: 2
      when_failed: "when_failed"
  SmartSsd_ata_smart_attributes:
    properties:
      revision:
        type: "integer"
        format: "int32"
      table:
        type: "array"
        items:
          $ref: "#/definitions/SmartSsd_ata_smart_attributes_table"
    example:
      table:
      - name: "name"
        flags:
          error_rate: true
          performance: true
          string: "string"
          updated_online: true
          auto_keep: true
          event_count: true
          prefailure: true
          value: 6
        raw:
          string: "string"
          value: 1
        worst: 1
        id: 3
        value: 6
        thresh: 2
        when_failed: "when_failed"
      - name: "name"
        flags:
          error_rate: true
          performance: true
          string: "string"
          updated_online: true
          auto_keep: true
          event_count: true
          prefailure: true
          value: 6
        raw:
          string: "string"
          value: 1
        worst: 1
        id: 3
        value: 6
        thresh: 2
        when_failed: "when_failed"
      revision: 6
  SmartSsd_temperature:
    properties:
      current:
        type: "integer"
        format: "int32"
      power_cycle_min:
        type: "integer"
        format: "int32"
      power_cycle_max:
        type: "integer"
        format: "int32"
      lifetime_min:
        type: "integer"
        format: "int32"
      lifetime_max:
        type: "integer"
        format: "int32"
      op_limit_min:
        type: "integer"
        format: "int32"
      op_limit_max:
        type: "integer"
        format: "int32"
      limit_min:
        type: "integer"
        format: "int32"
      limit_max:
        type: "integer"
        format: "int32"
    example:
      op_limit_max: 0
      current: 6
      op_limit_min: 7
      limit_min: 7
      power_cycle_max: 6
      lifetime_min: 3
      power_cycle_min: 5
      lifetime_max: 3
      limit_max: 6
  SmartSsd_ata_log_directory_table:
    properties:
      address:
        type: "integer"
        format: "int32"
      name:
        type: "string"
      read:
        type: "boolean"
      write:
        type: "boolean"
      gp_sectors:
        type: "integer"
        format: "int32"
      smart_sectors:
        type: "integer"
        format: "int32"
    example:
      address: 8
      read: true
      name: "name"
      gp_sectors: 7
      smart_sectors: 3
      write: true
  SmartSsd_ata_log_directory:
    properties:
      gp_dir_version:
        type: "integer"
        format: "int32"
      smart_dir_version:
        type: "integer"
        format: "int32"
      smart_dir_multi_sector:
        type: "boolean"
      table:
        type: "array"
        items:
          $ref: "#/definitions/SmartSsd_ata_log_directory_table"
    example:
      smart_dir_multi_sector: true
      gp_dir_version: 0
      table:
      - address: 8
        read: true
        name: "name"
        gp_sectors: 7
        smart_sectors: 3
        write: true
      - address: 8
        read: true
        name: "name"
        gp_sectors: 7
        smart_sectors: 3
        write: true
      smart_dir_version: 4
  SmartSsd_ata_smart_error_log_extended:
    properties:
      revision:
        type: "integer"
        format: "int32"
      sectors:
        type: "integer"
        format: "int32"
      count:
        type: "integer"
        format: "int32"
    example:
      sectors: 7
      count: 5
      revision: 3
  SmartSsd_ata_smart_error_log:
    properties:
      extended:
        $ref: "#/definitions/SmartSsd_ata_smart_error_log_extended"
    example:
      extended:
        sectors: 7
        count: 5
        revision: 3
  SmartSsd_ata_sct_status_temperature:
    properties:
      current:
        type: "integer"
        format: "int32"
      power_cycle_min:
        type: "integer"
        format: "int32"
      power_cycle_max:
        type: "integer"
        format: "int32"
      lifetime_min:
        type: "integer"
        format: "int32"
      lifetime_max:
        type: "integer"
        format: "int32"
      under_limit_count:
        type: "integer"
        format: "int32"
      over_limit_count:
        type: "integer"
        format: "int32"
    example:
      current: 0
      power_cycle_max: 4
      lifetime_min: 1
      over_limit_count: 9
      power_cycle_min: 6
      lifetime_max: 4
      under_limit_count: 7
  SmartSsd_ata_sct_status:
    properties:
      format_version:
        type: "integer"
        format: "int32"
      sct_version:
        type: "integer"
        format: "int32"
      device_state:
        $ref: "#/definitions/SmartSsd_ata_smart_data_offline_data_collection_status"
      temperature:
        $ref: "#/definitions/SmartSsd_ata_sct_status_temperature"
      vendor_specific:
        type: "array"
        items:
          type: "integer"
          format: "int32"
    example:
      device_state:
        string: "string"
        value: 1
      format_version: 3
      sct_version: 4
      temperature:
        current: 0
        power_cycle_max: 4
        lifetime_min: 1
        over_limit_count: 9
        power_cycle_min: 6
        lifetime_max: 4
        under_limit_count: 7
      vendor_specific:
      - 0
      - 0
  SmartSsd_ata_sct_temperature_history_temperature:
    properties:
      op_limit_min:
        type: "integer"
        format: "int32"
      op_limit_max:
        type: "integer"
        format: "int32"
      limit_min:
        type: "integer"
        format: "int32"
      limit_max:
        type: "integer"
        format: "int32"
    example:
      op_limit_max: 4
      op_limit_min: 5
      limit_min: 6
      limit_max: 8
  SmartSsd_ata_sct_temperature_history:
    properties:
      version:
        type: "integer"
        format: "int32"
      sampling_period_minutes:
        type: "integer"
        format: "int32"
      logging_interval_minutes:
        type: "integer"
        format: "int32"
      temperature:
        $ref: "#/definitions/SmartSsd_ata_sct_temperature_history_temperature"
      size:
        type: "integer"
        format: "int32"
      index:
        type: "integer"
        format: "int32"
      table:
        type: "array"
        items:
          type: "integer"
          format: "int32"
    example:
      size: 4
      logging_interval_minutes: 7
      sampling_period_minutes: 0
      temperature:
        op_limit_max: 4
        op_limit_min: 5
        limit_min: 6
        limit_max: 8
      index: 3
      version: 9
      table:
      - 0
      - 0
  SmartSsd_ata_sct_erc:
    properties:
      read:
        $ref: "#/definitions/SmartSsd_read_lookahead"
      write:
        $ref: "#/definitions/SmartSsd_read_lookahead"
    example:
      read:
        enabled: true
      write:
        enabled: true
  SmartSsd_sata_phy_event_counters_table:
    properties:
      id:
        type: "integer"
        format: "int32"
      name:
        type: "string"
      size:
        type: "integer"
        format: "int32"
      value:
        type: "integer"
        format: "int32"
      overflow:
        type: "boolean"
    example:
      overflow: true
      size: 1
      name: "name"
      id: 2
      value: 8
  SmartSsd_sata_phy_event_counters:
    properties:
      table:
        type: "array"
        items:
          $ref: "#/definitions/SmartSsd_sata_phy_event_counters_table"
      reset:
        type: "boolean"
    example:
      reset: true
      table:
      - overflow: true
        size: 1
        name: "name"
        id: 2
        value: 8
      - overflow: true
        size: 1
        name: "name"
        id: 2
        value: 8
  inline_response_200:
    properties:
      UUID:
        type: "string"
        description: "Unique User ID"
      ApiKey:
        type: "string"
        description: "API Key"
    example:
      ApiKey: "ApiKey"
      UUID: "UUID"
